name: clothing_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  google_sign_in: ^6.0.2
  share_plus: ^10.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/hoodie.png
  - assets/images/sneakers.png
  - assets/images/profile.jpg
  - assets/images/shirt.png
  - assets/images/jeans.png
  - assets/images/jacket.png
  - assets/images/tshirt.png
  - assets/images/onboarding1.png
  - assets/images/onboarding2.png
  - assets/images/onboarding3.png
  